### ISSUE TITLE
`gophernotes` panics

### ISSUE THREAD

**Issue by kevinburke** [gopherds/gophernotes#28] opened 2016-06-15 03:14 UTC
I tried running with the `--debug` flag on but didn't get debug output, instead I commented out the `if !debug` check in replpkg/log.go to force debug logging, and got the following info:

```
repl.go:118 could not import "github.com/k0kubun/pp": can't find import: github.com/k0kubun/pp
repl.go:118 could not import "github.com/davecgh/go-spew/spew": can't find import: github.com/davecgh/go-spew/spew
repl.go:118 could not import "fmt": reading export data: /Users/kevin/go/pkg/darwin_amd64/fmt.a: import error /Users/kevin/go/pkg/darwin_amd64/fmt.a:1:4 (byte offset = 3): expected keyword package, got "cn"
```

I'm guessing these don't get installed because they're not explicitly dependencies? I'm wondering if there's a way to force `go get` to install them or at the very least mention it in the README.

**Comment by kevinburke** [comment] 2016-06-15 03:35
FWIW it seems like the binary format changed in 1.7. I tried updating the `go/types` dependency but ran into trouble doing that.

**Comment by dwhitena** [comment] 2016-06-21 20:01
@kevinburke Great comment.  Thanks.  I need to experiment a little more with 1.7 and find associated weirdness.  So, did you successfully get it working with 1.7 without --debug?

**Comment by kevinburke** [comment] 2016-07-08 03:49
I did not

**Comment by kevinburke** [comment] 2016-07-08 03:49
I ran it without debug but manually added comments to get it to print out errors and it wasn't working

**Comment by dwhitena** [comment] 2016-07-29 12:32
Hi @kevinburke I just updated to use `go/types` and the dependencies.  Could you try installing the latest in `master` and let me know if the issue is resolved?  Thanks!

**Comment by dwhitena** [comment] 2016-08-01 12:17
My understanding is that this is resolved.  Closing.

**Closed by dwhitena** 2016-08-01 12:17 UTC
